export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  USERS: '/users',
  USER_DETAIL: (id: string) => `/users/${id}`,
  COURSES: '/courses',
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  COURSE_CREATE: '/courses/new',
  COURSE_EDIT: (id: string) => `/courses/${id}/edit`,
  COURSE_IMPORT: '/courses/import',
  LABS: '/labs',
  LAB_DETAIL: (id: string) => `/labs/${id}`,
  LAB_CREATE: '/labs/new',
  LAB_EDIT: (id: string) => `/labs/${id}/edit`,
  UN_AUTHORIZED: '/401',
  PATHS: '/paths',
  PATH_DETAIL: (id: string) => `/paths/${id}`,
  PATH_CREATE: '/paths/create',
  PATH_EDIT: (id: string) => `/paths/${id}/edit`,
} as const;
